/*==============================================================*/
/* Table: CIUDAD                                                */
/*==============================================================*/
/*create table CIUDAD (
   ID_CIUDAD            varchar(2)            not null,
   NOMBRE               varchar(20)           not null,
   constraint PK_CIUDAD primary key (ID_CIUDAD)
);*/

INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Le', 'Leticia');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Me', 'Medellín');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Ar', 'Arauca');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Ba', 'Barranquilla');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Bo', 'Bogotá');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Ca', 'Cartagena de Indias');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Tu', 'Tunja');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Ma', 'Manizales');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Fl', 'Florencia');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Yo', 'Yopal');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Po', 'Popayán');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Va', 'Valledupar');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Qu', 'Quibdó');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Mo', 'Montería');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Bo', 'Bogotá');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('In', 'Inírida');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Sa', 'San José del Guaviare');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Ne', 'Neiva');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Ri', 'Riohacha');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Sa', 'Santa Marta');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Vi', 'Villavicencio');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Pa', 'Pasto');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Sa', 'San José de Cúcuta');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Mo', 'Mocoa');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Ar', 'Armenia');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Pe', 'Pereira');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Sa', 'San Andrés');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Bu', 'Bucaramanga');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Si', 'Sincelejo');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Ib', 'Ibagué');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Ca', 'Cali');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Mi', 'Mitú');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Pu', 'Puerto Carreño');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Bu', 'Buga');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Ch', 'Chia');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Co', 'Cota');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Fa', 'Facatativá');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('To', 'Tocancipá');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Fu', 'Funza');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Me', 'La Mesa');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Vi', 'Villeta');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Zi', 'Zipaquirá');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('So', 'Soacha');
